gen:
	./codegen.sh

build:
	mkdir -p ./bin/debug
	go build -o ./bin/debug/dapp-payment-api .

start:
	./start.sh

stop:
	./stop.sh

apikeygen:
	mkdir -p ./bin/debug
	go build -o ./bin/debug/api-key-gen ./tool/api_key_gen
