name: euruswallet
description: Crypto wallet example
version: 0.1.0
homepage: https://www.goldhub.hk

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  flutter_easyloading: ^3.0.0
  qr_flutter: ^4.0.0
  pin_code_fields: ^7.3.0
  material_segmented_control: ^3.1.2
  fluttertoast: ^8.0.8
  webview_flutter: ^2.0.10
  livechat_inc:
    git:
      url: https://github.com/gavinlau18m/livechat_inc.git
      ref: master
  uni_links: ^0.5.1
  share: ^2.0.4
  flutter_reorderable_list:
    git:
      url: https://github.com/dkobia/flutter_reorderable_list.git
      ref: update-to-2.6.0
  app_transaction_manager:
    git:
      url: https://github.com/eurus-chain/eurus-app-transaction-manager
      ref: development/main
  app_crypto_icons:
    git:
      url: https://github.com/eurus-chain/eurus-app-crypto-icon
      ref: 51b3d7b66ce52e96c26755f0ccc9da2d2003e86c
  percent_indicator: ^3.0.1
  screenshot: ^1.2.3
  package_info: ^2.0.2
  apihandler:
    git:
      url: https://github.com/eurus-chain/eurus-app-network
      ref: main
  app_qrcode_scanner:
    git:
      url: https://github.com/eurus-chain/eurus-app-qrcode-scanner
      ref: development/main
  # biometric_storage: ^1.1.0+1
  # biometric_storage:
  #   path: ../biometric_storage
  biometric_storage:
    git:
      url: https://github.com/eurus-chain/biometric_storage
      ref: EURUS/main
  permission_handler: ^8.1.4+2
  http: ^0.13.3
  url_launcher: ^6.0.9
  rxdart: ^0.26.0
  app_authentication_kit:
    git:
      url: https://github.com/eurus-chain/eurus-app-authentication
      ref: development/main
  app_security_kit:
    git:
      url: https://github.com/eurus-chain/eurus-app-security
      ref: development/main
  # curved_navigation_bar: ^0.3.7 #latest version
  #  curved_navigation_bar:
  #    git:
  #      url: https://github.com/eurus-chain/eurus-app-wallet-ui-bottom_navigation_bar
  #      ref: EURUS/main
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  device_info: ^2.0.2
  web3dart: ^2.3.1
  decimal: ^1.3.0
  camera: ^0.8.1+7
  path_provider: ^2.0.2
  path: ^1.8.0
  image: ^3.0.2
  dio: ^4.0.0
  flutter_jailbreak_detection: 1.8.0
  screenshot_callback:
    git:
      url: https://github.com/ousvat/flutter_screenshot_callback
      ref: master
  rounded_loading_button: ^2.0.5
  flutter_slidable: ^0.6.0
  bip39: ^1.0.3
  bs58check: ^1.0.1
  meta: 1.7.0
  bech32: ^0.2.0
  flutter_inappwebview: ^5.3.2
  flutter_web3_provider: ^1.0.6
  flutter_neumorphic:
    git:
      url: https://github.com/tsvillain/Flutter-Neumorphic
  metadata_fetch: ^0.4.1
  favicon: ^1.0.15
  loader_overlay: ^2.0.2+1
  flutter_svg: ^0.22.0
  eth_sig_util: ^0.0.6
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_crashlytics: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.euruswallet
        pluginClass: EuruswalletPlugin
      ios:
        pluginClass: EuruswalletPlugin
      web:
        pluginClass: EuruswalletPlugin

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - lib/i18n/
    - lib/pages/dappBrowser/web3_ethereum_setup.js

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: fonts/SFProDisplay-Bold.ttf
          weight: 700

  uses-material-design: true
