language: node_js
node_js: 12.0.0
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_56eb988ff061_key -iv $encrypted_56eb988ff061_iv -in sit.pem.enc -out sit.pem -d
- chmod 600 sit.pem
install:
- npm i
script:
- npm run build
after_success:
- scp -r -i sit.pem -o stricthostkeychecking=no ~/build/eurus-chain/eurus-block-explorer/dist
  centos@18.166.159.174:/opt/block-explorer
- rm sit.pem
branches:
  only:
  - testing
