apiVersion: v1
kind: Secret
metadata:
  name: besu-node1-key
  labels:
    app: besu-node1-key
  namespace: besu
type: Opaque
stringData:
  key: "0xae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f"
