---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node2privacy
  labels:
    app: node2privacy
  namespace: besu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node2privacy
  serviceName: besu-node2privacy
  template:
    metadata:
      labels:
        app: node2privacy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9545"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: node2privacy
          image: hyperledger/besu:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VALIDATOR1_PUBKEY
              valueFrom:
                configMapKeyRef:
                  name: besu-validators-configmap
                  key: validator1PubKey
            - name: VALIDATOR2_PUBKEY
              valueFrom:
                configMapKeyRef:
                  name: besu-validators-configmap
                  key: validator2PubKey
          volumeMounts:
            - name: genesis-config
              mountPath: /etc/genesis
              readOnly: true
            - name: config-toml
              mountPath: /etc/besu
              readOnly: true
            - name: data
              mountPath: /data
            - name: orion-pubkey
              mountPath: /configs/orion
              readOnly: true
          ports:
            - containerPort: 8545
              name: json-rpc
              protocol: TCP
            - containerPort: 8546
              name: ws
              protocol: TCP
            - containerPort: 8547
              name: graphql
              protocol: TCP
            - containerPort: 30303
              name: rlpx
              protocol: TCP
            - containerPort: 30303
              name: discovery
              protocol: UDP
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec /opt/besu/bin/besu \
                --config-file=/etc/besu/config.toml \
                --privacy-enabled=true \
                --privacy-url=http://${BESU_ORION2_SERVICE_HOST}:8888 \
                --privacy-public-key-file=/configs/orion/orion.pub \
                --Xnat-kube-service-name=besu-node2privacy \
                --bootnodes=enode://${VALIDATOR1_PUBKEY}@${BESU_VALIDATOR1_SERVICE_HOST}:30303,enode://${VALIDATOR2_PUBKEY}@${BESU_VALIDATOR2_SERVICE_HOST}:30303
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8545
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: orion-pubkey
          configMap:
            name: orion-configmap
            items:
              - key: orion1PubKey
                path: orion.pub
        - name: genesis-config
          configMap:
            name: besu-genesis-configmap
        - name: config-toml
          configMap:
            name: besu-config-toml-configmap
        - name: data
          emptyDir:
            sizeLimit: "1Gi"